# **Lab 1:** Implementing a solver for systems of linear equations

Edit this box and list the group components:
*   Member 1
*   Member 2


---

## Setting up the environment:
---



Mount drive:

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Download extra files and move them to drive folder. **IMPORTANT:** Run this cell only once. Delete it as soon as it has been executed to avoid further problems.

In [3]:
!wget https://raw.githubusercontent.com/jul-upc/citm_22_23/main/Labs/lab1/lab1_functions.py
!mkdir -p drive/MyDrive/mathsvjII/lab1
!mv lab1_functions.py drive/MyDrive/mathsvjII/lab1/lab1_functions.py 

--2022-10-11 13:35:43--  https://raw.githubusercontent.com/jul-upc/citm_22_23/main/Labs/lab1/lab1_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 748 [text/plain]
Saving to: ‘lab1_functions.py’

lab1_functions.py   100%[===================>]     748  --.-KB/s    in 0s      

2022-10-11 13:35:44 (38.9 MB/s) - ‘lab1_functions.py’ saved [748/748]



Import modules to be created. This cell needs to be executed every time the file lab1_functions.py changes!

In [6]:
import sys
sys.path.append('/content/drive/My Drive/mathsvjII/lab1/')
from lab1_functions import naive_forward_elimination, forward_elimination, backtracking

Import the system modules as needed

In [7]:
import numpy as np



---


## **Exercise 1:**

Implement and test a backtracking substitution function. 

### 1.1:
Implement the backtracking function in the lab1_functions.py file.
Input arguments should be At and bt representing a Triangular matrix and an independent term vector. The output of the function should be the solution vector $\boldsymbol{x}$ such that $\boldsymbol{A}_t\boldsymbol{x}=\boldsymbol{b}_t$

### 2.1:

Test the implemented function inside this notebook. To this end generate a **couple** of triangular systems for which you know the answer. The purpose of this section is to **TEST** your function, so consider complex cases, e.g., system dimensions > 4



---


## **Exercise 2:**

Implement and test a naïve forward elimination function 

### 2.1:
Implement the naive_forward_elimination function in the lab1_functions.py file.
Input arguments should be A and b representing a generic square matrix and an independent term vector. The output of the function should be an equivalent system represented by At, bt with At triangular.

Use the expression
$$ \boldsymbol{r}_j = a_{pp} \boldsymbol{r}_j - a_{jp}\boldsymbol{r}_p\quad \forall j>p $$
to make 0 under the pivot $a_{pp}$


### 2.2:

Test the implemented function inside this notebook. To this end generate a **couple** of systems for which you know the answer. The purpose of this section is to **TEST** your function, so consider complex cases, e.g., system dimensions > 4.

Find the solutions to the proposed system by calling first the naive_forward_elimination() function and after, the backtracking function already implemented in the above exercise.



---


## **Exercise 3:**

Improve the forward elimination

### 3.1:
Implement the forward_elimination function in the lab1_functions.py file.
Input arguments should be A and b representing a generic square matrix and an independent term vector. The output of the function should be an equivalent system represented by At, bt with At triangular. However, this time:



*   Use the expression
$$ \boldsymbol{r}_j =  \boldsymbol{r}_j - a_{jp}/a_{pp} \boldsymbol{r}_p\quad \forall j>p $$
to make 0 under the pivot $a_{pp}$
*   Implement the partial pivoting to chose at each iteration of the forward elimination the best row to pivot with.

*   The function should return also a bolean variable associated with the uniqueness of the system solution. If true, the system has a unique solution, otherwise (False) the system has either many or none solutions.






### 3.2:

Test the implemented function inside this notebook. To this end generate a **couple** of systems for which you know the answer. The purpose of this section is to **TEST** your function, so consider complex cases, e.g., system dimensions > 4.

Find the solutions to the proposed system by calling first the naive_forward_elimination() function and after, the backtracking function already implemented in the above exercise.



### 3.3:

Test both functions for forward elimination with the next system of equations:
$$ x+2y+3z = 14$$
$$ x+2y-2z = -1$$
$$ y+2z = 8$$

### 3.4: 

Create a system of equations with multiple solutions and one without solution. Try to solve both systems using the two forward elimination functions and comment the result.





---
---
# **Additional info:** 




Big number issue:

In [ ]:
a = 1E99
b = 1E99+1
print(a-b)

0.0




---



**HOW TO:** Swap to rows

Given a matrix A,  
`A[[i,j],:] = A[[j,i],:] `  
swaps rows i and j.

In the next example the matrix A is a random created 6x6 matrix and then the 2nd and 6th rows (indexes 1 and 5) are exchanged

In [6]:
A = np.random.rand(6,6)
print('A =', A,"\n")
A[[1,5],:] = A[[5,1],:]
print("A swapped=",A)

print(type(A))

A = [[0.05357236 0.01221236 0.58165656 0.52359506 0.90662332 0.41671282]
 [0.08017041 0.20062922 0.34969525 0.04659676 0.9175846  0.61504843]
 [0.50861281 0.3817688  0.86834609 0.67068405 0.80685987 0.91543537]
 [0.96496688 0.8146323  0.95658797 0.02033569 0.60089896 0.23489521]
 [0.96093135 0.89073761 0.95159881 0.36086317 0.86690587 0.53862592]
 [0.12177215 0.64939733 0.24019044 0.00815078 0.33716567 0.86830656]] 

A swapped= [[0.05357236 0.01221236 0.58165656 0.52359506 0.90662332 0.41671282]
 [0.12177215 0.64939733 0.24019044 0.00815078 0.33716567 0.86830656]
 [0.50861281 0.3817688  0.86834609 0.67068405 0.80685987 0.91543537]
 [0.96496688 0.8146323  0.95658797 0.02033569 0.60089896 0.23489521]
 [0.96093135 0.89073761 0.95159881 0.36086317 0.86690587 0.53862592]
 [0.08017041 0.20062922 0.34969525 0.04659676 0.9175846  0.61504843]]
<class 'numpy.ndarray'>


---

**HOW TO:** Search for the maximum entry into a vector

Use the function `np.argmax(L)` to find the position index `j`, for which `L[j]` is the maximum entry in `L`.

In the next example we would like to find the row wich contains the best pivot to continue with a triangulation process of matrix `B`. `L` represents the vector of considered entries and `m` is the position of the best pivot (the farthest from 0) in `L`.

In [5]:
B = np.array([[ 0.66207722,  0.52655123,  -0.25817321,  0.08355348,  -0.67190337,  0.36463801],
    [ 0,  -0.56111226, -0.96739743, -0.90302233, -0.09202517, -0.54174931],
    [ 0,   0,           0.08650408,  0.71455831,  0.38972072,  0.31245884],
    [ 0,   0,           0.59489716,  -0.07148201,  -0.57395873,  0.69406166],
    [ 0,   0,          -0.95005076,  0.53283380,   0.37666519,  -0.05645905],
    [ 0,   0,          -0.27707964, -0.74979451, -0.76113234, -0.03147524]])

print(B)

L = B[2:,2]
print(L,'\n')
m = np.argmax(abs(L))
print(m)
print(L[m])

[[ 0.66207722  0.52655123 -0.25817321  0.08355348 -0.67190337  0.36463801]
 [ 0.         -0.56111226 -0.96739743 -0.90302233 -0.09202517 -0.54174931]
 [ 0.          0.          0.08650408  0.71455831  0.38972072  0.31245884]
 [ 0.          0.          0.59489716 -0.07148201 -0.57395873  0.69406166]
 [ 0.          0.         -0.95005076  0.5328338   0.37666519 -0.05645905]
 [ 0.          0.         -0.27707964 -0.74979451 -0.76113234 -0.03147524]]
[ 0.08650408  0.59489716 -0.95005076 -0.27707964] 

2
-0.95005076


---

**HOW TO:** Concatenate two matrices

Use the functions 

*   `np.concatenate((A, B), axis = 0)` to stack two matrixes along the vertical direction
*   `np.concatenate((A, B), axis = 1)` to stack two matrixes along the horizontal direction

Alternatives also exist, e.g., np.hstack(), np.vstack().

The next example takes two matrices and concatenates them in the vertical direction.


 

In [10]:
A = np.random.rand(4,4)
B = np.random.rand(2,4)

print("A = ", A, "\n")
print("B = ", B, "\n")

C = np.concatenate((A,B), axis = 0)
print("C = ", C, "\n")
C2 = np.vstack((A,B))
print("C = ", C2, "\n")

A =  [[0.61319424 0.75777579 0.69224229 0.38080204]
 [0.04787482 0.46712267 0.96250015 0.99982833]
 [0.14325826 0.17764917 0.34610592 0.98990842]
 [0.57628847 0.97755698 0.18455843 0.10796077]] 

B =  [[0.95883353 0.07750782 0.8790196  0.34236876]
 [0.59519182 0.33880636 0.93909379 0.29443256]] 

C =  [[0.61319424 0.75777579 0.69224229 0.38080204]
 [0.04787482 0.46712267 0.96250015 0.99982833]
 [0.14325826 0.17764917 0.34610592 0.98990842]
 [0.57628847 0.97755698 0.18455843 0.10796077]
 [0.95883353 0.07750782 0.8790196  0.34236876]
 [0.59519182 0.33880636 0.93909379 0.29443256]] 

C =  [[0.61319424 0.75777579 0.69224229 0.38080204]
 [0.04787482 0.46712267 0.96250015 0.99982833]
 [0.14325826 0.17764917 0.34610592 0.98990842]
 [0.57628847 0.97755698 0.18455843 0.10796077]
 [0.95883353 0.07750782 0.8790196  0.34236876]
 [0.59519182 0.33880636 0.93909379 0.29443256]] 

